[package]
name = "hello-rust-rocket"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
chrono = "0.4"
rocket = "0.5.0-rc.1"

[dev-dependencies]
cargo-watch = "7.8.1"